<img style="float: left; width: 100px; height: auto;" src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg"/>


<h1 style="text-align: center;">Guide d'utilisation de NumPy</h1>



## Introduction à [NumPy](https://numpy.org/doc/stable/user/basics.html)


NumPy est une bibliothèque Python utilisée pour le calcul numérique. Elle fournit un support pour les tableaux multidimensionnels, ainsi que des fonctions pour effectuer des opérations mathématiques sur ces tableaux. Voici un guide pour bien démarrer avec NumPy.


## Installation

Nous pouvons l'installer via pip :

In [1]:
# pip install numpy    # Nous n'avons pas besoin de l'installer sur Jupyter

## Importation

Pour utiliser NumPy dans notre code Python, importons-le de la manière suivante :


In [2]:
import numpy as np

## Création de tableaux

### Tableaux à une dimension (vecteurs)


In [3]:
# À partir d'une liste ou d'un tuple
vecteur1 = np.array([1, 2, 3, 4, 5])

# À partir d'une plage
vecteur2 = np.arange(1, 6)

# Vecteur de zéros
vecteur3 = np.zeros(5)

# Vecteur de uns
vecteur4 = np.ones(5)

# Vecteur aléatoire (distribution uniforme)
vecteur5 = np.random.rand(5)

In [4]:
print(vecteur1)
print(vecteur2)
print(vecteur5)

[1 2 3 4 5]
[1 2 3 4 5]
[0.92774541 0.01662868 0.37866272 0.00993845 0.92949015]


In [5]:
# Générer un vecteur séparé par un interval fixe : arange(début,fin,pas,dtype)
print(np.arange(5))

# Générer un vecteur espacé linéairement : linspace(début,fin,nombre de points)
print(np.linspace(-6,3,5)) 

[0 1 2 3 4]
[-6.   -3.75 -1.5   0.75  3.  ]


### Tableaux à deux dimensions (matrices)

In [6]:
# À partir de listes/tuples imbriquées
matrice1 = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

# Matrice identité
matrice2 = np.eye(3) # De dimension (3,3)

# Matrice de zéros
matrice3 = np.zeros((3, 3))

# Matrice de uns
matrice4 = np.ones((3, 3))

# Matrice aléatoire (distribution uniforme)
matrice5 = np.random.rand(3, 3)

# Matrice aléatoire (distribution normale) aux dimensions 2x3
matrice6 = np.random.randn(2, 3)

# Matrice d'entiers aléatoires de 0 a 10 et de dimension 2x3
matrice7 = np.random.randint(0, 10, [2, 3])

# Matrice de valeurs identiques
matrice8 = np.full((2,3), 10)

In [7]:
print(matrice6)

[[ 0.70850024  1.42874265  1.54817807]
 [ 1.54680767 -1.65324317 -0.63657298]]


## Accès aux éléments (indexing et slicing)

In [8]:
vecteur1 = np.array([1,2,3,4,5,6])

# Accès à un élément (indexing) : [index]
print(vecteur1[0])

# Accès à une tranche (slicing) : [début:fin:pas]
print(vecteur1[1:5:2])

matrice1 = np.array([[1,2],[3,4]])

# Accès à un élément spécifique dans une matrice
print(matrice1[0][1])

1
[2 4]
2


## Boolean indexing

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6]])

# Masque booléen
print(A<5)
 
# Sous-ensemble filtré par le masque booléen
print(A[A < 5])
 
# Convertir les valeurs sélectionnées
A[A<5] = 4 

print(A)

[[ True  True  True]
 [ True False False]]
[1 2 3 4]
[[4 4 4]
 [4 5 6]]


## Format et Dimension

In [10]:
matrice1 = np.array([[1,2],[3,4]])

# Dimension d'un tableau
print(matrice1.ndim)

# Nombre d'éléments dans un tableau
print(matrice1.size)

# N-uplet indiquant la longueur pour chaque dimension du tableau
print(matrice1.shape)

# Longueur d'un array
len(matrice1)

2
4
(2, 2)


2

## Modification des éléments

In [11]:
# Remplacer les valeurs d’un tableau
matriceA = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
matriceA[0] = [11, 22, 33]
print(matriceA)

[[11 22 33]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# Remplacement par un unique scalaire
matriceA[0] = 100
print(matriceA)

# Remplacement avec Slicing
matriceA[0:2] = 100
print(matriceA)

[[100 100 100]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
[[100 100 100]
 [100 100 100]
 [  7   8   9]
 [ 10  11  12]]


## Manipulation des Arrays

In [13]:
# Redimensionner un tableau
matrice = np.zeros((2, 3))
print(matrice.reshape((3,2)))
print(matrice.reshape((1,6)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0. 0.]]


In [14]:
# Applatir un tableau (il ne fait plus qu'une dimension)
print(matrice.ravel())
print("-"*10)

# Assembler 2 tableaux selon un axe (similaire à hstack et vstack)
matrice9 = np.ones((2,3))
print(np.concatenate((matrice, matrice9), axis=0)) # axe 0 : équivalent de np.vstack((matrice, matrice9))
print("-"*10)
print(np.concatenate((matrice, matrice9), axis=1)) # axe 1 : équivalent de np.hstack((matrice, matrice9))

[0. 0. 0. 0. 0. 0.]
----------
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [15]:
# Ajouter une colonne à une matrice
matriceB = np.array([[1,2,3], [5,6,7]])

ajout_col = np.array([[4], [8]])
matriceB = np.append(matriceB,ajout_col, axis = 1)
print(matriceB)

# Ajouter une ligne à une matrice
matriceC = np.array([[1,5,7], [8,3,7]])
matriceC = np.vstack([matriceC,np.array([10, 11, 12])])
print(matriceC)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  5  7]
 [ 8  3  7]
 [10 11 12]]


Pour copier un tableau il ne faut pas faire un "=" mais un "Mat = mat_à_copier.copy()"

## Fonctions mathématiques

In [16]:
vecteurA = np.array([1,2,3,4])
vecteurB = np.array([5,6,7,8])

# Fonctions trigonométriques
print(np.sin(vecteurA))
print(np.cos(vecteurA))

# Fonctions exponentielles et logarithmiques
print(np.exp(vecteurA))
print(np.log(vecteurA))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


## Opérations mathématiques
NumPy fournit des fonctions pour effectuer des opérations mathématiques sur les tableaux.

In [17]:
# Addition
print(np.add(vecteurA, vecteurB))

# Soustraction
print(np.subtract(vecteurA, vecteurB))

# Multiplication (de termes à termes)
print(np.multiply(vecteurA, vecteurB))

# Division
print(np.divide(vecteurA, vecteurB))

# Produit scalaire & Produit matriciel
print(np.dot(vecteurA, vecteurB))

# Transposé d'une matrice : métode np.transpose() ou attribut vecteurA.T
print(np.transpose(vecteurA))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
70
[1 2 3 4]


Pour le produit scalaire : 
$a \cdot b = \sum_{i=1}^{n} a_i \times b_i$


Où $a_i$ et $b_i$ sont les composantes des vecteurs a et b, respectivement.

# Somme, Produit d'une matrice

<img src="./Images/image1.png" alt="Visualisation des axes Numpy" width="300" height="auto" style="float: left;"/>

In [18]:
A = np.array([[5, 0, 3], [3, 7, 9]])

# Somme de tous les éléments du tableau
print(A.sum()) 

# Somme des colonnes (somme sur les éléments des lignes)
print(A.sum(axis=0)) 

# Somme des lignes (somme sur les éléments des colonnes)
print(A.sum(axis=1)) 

# Somme cumulée
print(A.cumsum(axis=0))
 
# Produit et Produit cumulé
print(A.prod()) 
print(A.cumprod())
 

# Fonctions statistiques
print(A.min())
print(A.max())
print(A.mean())
print(np.median(A))
print(np.std(A))

27
[ 8  7 12]
[ 8 19]
[[ 5  0  3]
 [ 8  7 12]]
0
[5 0 0 0 0 0]
0
9
4.5
4.0
2.9297326385411577


## [Algèbre Linéaire](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [19]:
B = np.array([[1,3],[7,9]])
C = np.array([4,5])

# Déterminant d'une matrice
print("o Le déterminant de B est :", np.linalg.det(B))

# Inverse d'une matrice
print("o L'inverse de B est :", np.linalg.inv(B))

# Résolution d’un système d’équations linéaires
x = np.linalg.solve(B, C)
print("o La solution de l'équation est :", x)

# Vérifier la solution à l'équation
np.allclose(np.dot(B, x), C)


D = np.array([[ 1, 1, -2 ], [-1, 2, 1], [0, 1, -1]])

# Valeurs propres et vecteurs propres
E, V = np.linalg.eig(D)
print("o", E)
print("o",V)

# Les colonnes de V sont les vecteurs propres de A associés aux valeurs propres qui apparaissent dans D

o Le déterminant de B est : -12.0
o L'inverse de B est : [[-0.75        0.25      ]
 [ 0.58333333 -0.08333333]]
o La solution de l'équation est : [-1.75        1.91666667]
o [ 2.  1. -1.]
o [[ 3.01511345e-01 -8.01783726e-01  7.07106781e-01]
 [ 9.04534034e-01 -5.34522484e-01 -1.92296269e-16]
 [ 3.01511345e-01 -2.67261242e-01  7.07106781e-01]]


## Génération d'une matrice avec des nombres pseudo-aléatoires

In [20]:
# Tirage de 5 valeurs
taille = 5 

# Nombres tirés d'une loi Uniforme [0,1]
print(np.random.rand(taille))

# Nombres tirés d'une loi Uniforme [a,b]
a, b = 0, 10
print(np.random.uniform(a,b,taille))

# Nombres tirés d'une loi Uniforme [a;b[
print(np.random.randint(a,b,taille))
 
# Nombres tirés d'une loi Normale centrée réduite
print(np.random.randn(taille))

# Nombres tirés d'une loi Normale d’espérance 10 et d’écart-type 4
print(np.random.normal(10, 4, taille))

# Nombres tirés d'une loi Binomiale (n,p)
print(np.random.binomial(10, 0.5, taille))
 
# Nombres tirés d'une loi bêta de paramètres 10 et 5
print(np.random.beta(10, 5, taille))

# Nombres tirés d'une loi de Poisson de paramètre 2
print(np.random.poisson(2, taille))

# Nombres tirés d'une loi de Student à 10 degrés de liberté
print(np.random.standard_t(10, taille))

[0.60042685 0.82090252 0.58149234 0.11548998 0.77466364]
[6.99064792 2.20055456 8.87694092 1.14754048 6.17187297]
[5 6 9 5 8]
[ 0.98449154  0.6293554  -0.15465325  1.08177638 -0.97639184]
[14.73103058  8.15826495  4.12125091 11.4369656  13.68846241]
[4 3 4 7 4]
[0.69029754 0.72297684 0.56308963 0.77756144 0.89701501]
[2 3 0 1 2]
[-0.30967268  0.81690714  1.10451966  2.21276321 -0.12002712]


Source pour la rédaction de ce notebook :
- https://numpy.org/doc/stable/user/basics.html